# Generated by Django 3.0.5 on 2020-04-13 15:12

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='faces',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
