# Generated by Django 3.0.5 on 2020-04-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200413_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='faces',
            field=models.CharField(default='', max_length=100),
        ),
    ]
