# Generated by Django 3.0.5 on 2020-04-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200413_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='facesNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='hash',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
