# Generated by Django 3.0.5 on 2020-04-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200413_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='hash',
        ),
        migrations.AddField(
            model_name='record',
            name='afterhash',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='record',
            name='beforehash',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
